name: Terragrunt Workflow

on:
  pull_request:
    branches: 
      - main
    types: [closed]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - qa
        - load
        - staging


permissions:
  id-token: write
  contents: read

jobs:
  terragrunt:
    runs-on: ubuntu-latest #runner
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 

      - name: PLAN
        run: |
          echo 'MY PLAN'
          sleep 10