name: Terragrunt Workflow

on:
  pull_request:
    branches: 
      - master
    types: [closed]
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  terragrunt:
    runs-on: ubuntu-latest #runner
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 

      - name: PLAN
        run: |
          echo 'jelo PLAN'
          sleep 10